/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package objetosNegocio.enums;

/**
 *
 * @author mdjes
 */
public enum Carrera {
    ARQUITECTURA,CONTADOR_PUBLICO,INGENIERIA_BIOMEDICA,INGENIERIA_EN_BIOTECNOLOGIA,INGENIERIA_EN_CIENCIAS_AMBIENTALES,
    INGENIERIA_CIVIL,INGENIERIA_EN_ELECTRONICA,INGENIERIA_EN_GEOCIENCIAS,INGENIERIA_EN_LOGISTICA,INGENIERIA_EN_MANUFACTURA,
    INGENIERIA_EN_MECATRONICA,INGENIERIA_EN_REDES_Y_TELECOMUNICACIONES,INGENIERIA_EN_SOFTWARE,INGENIERIA_INDUSTRIAL_Y_DE_SISTEMAS,
    INGENIERIA_QUIMICA,LICENCIATURA_EN_ADMINISTRACION,LICENCIATURA_EN_ADMINISTRACION_DE_EMPRESAS_TURISTICAS,
    LICENCIATURA_EN_CIENCIAS_DE_LA_EDUCACION,LICENCIATURA_EN_CIENCIAS_DEL_EJERCICIO_FISICO,LICENCIATURA_EN_DISEÑO_GRAFICO,
    LICENCIATURA_EN_DIRECCION_DE_LA_CULTURA_FISICA_Y_EL_DEPORTE,LICENCIATURA_EN_ECONOMIA_Y_FINANZAS,LICENCIATURA_EN_EDUCACION_ARTISTICA_Y_GESTION_CULTURAL,
    LICENCIATURA_EN_EDUCACION_INFANTIL,LICENCIATURA_EN_EMPRENDIMIENTO_E_INNOVACION,LICENCIATURA_EN_GASTRONOMIA,LICENCIATURA_EN_GESTION_Y_DESARROLLO_DE_LAS_ARTES,
    LICENCIATURA_EN_NUTRICION_HUMANA,LICENCIATURA_EN_PSICOLOGIA,LICENCIATURA_EN_SOCIOLOGIA,LICENCIATURA_EN_TECNOLOGIA_DE_ALIMENTOS,
    MEDICO_CIRUJANO,MEDICO_VETERINARIO_ZOOTECNISTA,QUIMICO_BIOLOGO_CLINICO
}
